### ISSUE TITLE
FileNotFound: rcsb-molstar.js

### ISSUE THREAD

**Issue by dtingey** [SSSSSimon/dash-molstar#2]
I installed using pip. I tried running just the example application:

```
import dash_molstar
from dash import Dash, html

app = Dash(__name__)

app.layout = html.Div(
    dash_molstar.MolstarViewer(
        id='viewer', style={'width': '500px', 'height':'500px'}
    ),
)

if __name__ == '__main__':
    print('Running...')
    app.run_server(debug=True)
```

But when I look in my browser it gives me this error:

```
FileNotFoundError
FileNotFoundError: [Errno 2] No such file or directory: '/home/****/mambaforge/envs/****/lib/python3.10/site-packages/dash_molstar/rcsb-molstar.js'

Traceback (most recent call last)
File "/home/****/mambaforge/envs/****/lib/python3.10/site-packages/flask/app.py", line 1482, in full_dispatch_request
rv = self.preprocess_request()
File "/home/****/mambaforge/envs/****/lib/python3.10/site-packages/flask/app.py", line 1974, in preprocess_request
rv = self.ensure_sync(before_func)()
File "/home/****/mambaforge/envs/****/lib/python3.10/site-packages/dash/dash.py", line 1318, in _setup_server
self._generate_scripts_html()
File "/home/****/mambaforge/envs/****/lib/python3.10/site-packages/dash/dash.py", line 821, in _generate_scripts_html
+ self._collect_and_register_resources(
File "/home/****/mambaforge/envs/****/lib/python3.10/site-packages/dash/dash.py", line 764, in _collect_and_register_resources
_relative_url_path(
File "/home/****/mambaforge/envs/****/lib/python3.10/site-packages/dash/dash.py", line 743, in _relative_url_path
modified = int(os.stat(module_path).st_mtime)
FileNotFoundError: [Errno 2] No such file or directory: '/home/****/mambaforge/envs/****/lib/python3.10/site-packages/dash_molstar/rcsb-molstar.js'
```

*Note: some path information excluded for privacy

I have python version 3.10.0, dash version 2.6.2

**Comment by dtingey** [comment]
I copied the `rcsb-molstar.js` file from github into my `dash_molstar` directory and it works. It would be nice to have it added to the pip install though if that is possible.

**Comment by SSSSSimon** [comment]
Thank you for reporting this issue. I have fixed the problem with the installation with pip. The latest 1.0.1 version now has the `rcsb-molstar.js` included.
